#!/bin/sh

# Semantic commit regex
commit_regex="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .{10,200}$"

# Merge commit regex
merge_commit_regex="^Merge (branch|remote-tracking branch) '.+' into .+$"

# Error message for non-compliant commits
error_msg="
Commit message does not follow semantic guidelines!

    Format: type(scope?): description

'types': feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
'scope': is optional but should describe the section of the codebase affected.
'description': should be a short description of what this commit does when applied.

Please fix your commit message and try again.
"

# Validate commit message
if ! grep -qE "$commit_regex" "$1" && ! grep -qE "$merge_commit_regex" "$1"; then
    echo "$error_msg"
    exit 1
fi

echo "Commit message follows semantic guidelines."
